/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedBorrowersRouteImport } from './routes/_authenticated/borrowers'
import { Route as AuthenticatedLoansIndexRouteImport } from './routes/_authenticated/loans.index'
import { Route as AuthenticatedLoansNewRouteImport } from './routes/_authenticated/loans.new'
import { Route as AuthenticatedLoansLoanIdRouteImport } from './routes/_authenticated/loans.$loanId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBorrowersRoute = AuthenticatedBorrowersRouteImport.update({
  id: '/borrowers',
  path: '/borrowers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLoansIndexRoute = AuthenticatedLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLoansNewRoute = AuthenticatedLoansNewRouteImport.update({
  id: '/loans/new',
  path: '/loans/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLoansLoanIdRoute =
  AuthenticatedLoansLoanIdRouteImport.update({
    id: '/loans/$loanId',
    path: '/loans/$loanId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/borrowers': typeof AuthenticatedBorrowersRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
  '/loans/new': typeof AuthenticatedLoansNewRoute
  '/loans/': typeof AuthenticatedLoansIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/borrowers': typeof AuthenticatedBorrowersRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/': typeof AuthenticatedIndexRoute
  '/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
  '/loans/new': typeof AuthenticatedLoansNewRoute
  '/loans': typeof AuthenticatedLoansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/borrowers': typeof AuthenticatedBorrowersRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
  '/_authenticated/loans/new': typeof AuthenticatedLoansNewRoute
  '/_authenticated/loans/': typeof AuthenticatedLoansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/borrowers'
    | '/contacts'
    | '/loans/$loanId'
    | '/loans/new'
    | '/loans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/borrowers'
    | '/contacts'
    | '/'
    | '/loans/$loanId'
    | '/loans/new'
    | '/loans'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/borrowers'
    | '/_authenticated/contacts'
    | '/_authenticated/'
    | '/_authenticated/loans/$loanId'
    | '/_authenticated/loans/new'
    | '/_authenticated/loans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/borrowers': {
      id: '/_authenticated/borrowers'
      path: '/borrowers'
      fullPath: '/borrowers'
      preLoaderRoute: typeof AuthenticatedBorrowersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loans/': {
      id: '/_authenticated/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof AuthenticatedLoansIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loans/new': {
      id: '/_authenticated/loans/new'
      path: '/loans/new'
      fullPath: '/loans/new'
      preLoaderRoute: typeof AuthenticatedLoansNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loans/$loanId': {
      id: '/_authenticated/loans/$loanId'
      path: '/loans/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof AuthenticatedLoansLoanIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBorrowersRoute: typeof AuthenticatedBorrowersRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLoansLoanIdRoute: typeof AuthenticatedLoansLoanIdRoute
  AuthenticatedLoansNewRoute: typeof AuthenticatedLoansNewRoute
  AuthenticatedLoansIndexRoute: typeof AuthenticatedLoansIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBorrowersRoute: AuthenticatedBorrowersRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLoansLoanIdRoute: AuthenticatedLoansLoanIdRoute,
  AuthenticatedLoansNewRoute: AuthenticatedLoansNewRoute,
  AuthenticatedLoansIndexRoute: AuthenticatedLoansIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
